name: 'Notifier Timeframe Setter'
description: 'Notifies to Slack when Bandit issues are found'
inputs:
  time-unit:
    description: 'time units: minutes'
    required: true
  interval:
    description: 'time interval for time unit'
    required: true
outputs:
  timeframe:
    description: 'calculated timeframe for input parameters'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.time-unit }}
    - ${{ inputs.interval }}
